apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sample-api-deployment.yaml
- sample-api-svc.yaml

images:
- name: kmin4/sample-api
  newTag: 0.0.28
- name: oscka/sample-api
  newTag: 0.0.24
